### PR TITLE
Add serde deserialization to AsId.

### PR DESCRIPTION
**Pull request by partim**
Adds deserialization of `repository::resources::AsId` via the `FromStr` impl.

### CODE REVIEW

**Comment by timbru** [comment]
Does it make sense to have serialization as well then? And a test which tests that serializing and then deserializing some corner case values results in equal things?

**Comment by partim** [comment]
I’ll add serialization. Should have done that right away.

For the tests, since the impls defer to `FromStr` and `Display`, maybe it is better to add tests to that?

**Comment by timbru** [comment]
Testing `FromStr` and `Display` also works I suppose. Though by going through serde you'd test both in one go. It would be good to test that "AS1", "as1", "As1" and "1" are all the same for `FromStr` even if `Display` prefers one option. I guess that's it pretty obvious from the code but I like having these sometimes.. mainly against regressions.

**Comment by partim** [comment]
@timbru Is that roughly what you had in mind?

**Review by timbru — APPROVED** [review]

**Pull request merged**
