### PR TITLE
Generate id cert

### PR DESCRIPTION
**Pull request by timbru**
Would like to merge this and then continue work on making a signed CMS message for the protocol messages. I.e. create an IdCert EE, CMS, sign, verify, etc. So some refactoring is bound in that context.

### CODE REVIEW

**Comment by mfontanini** [comment]
It looks like this PR broke some part of the certificate decoding. Is this a known issue?

You can test this by rsyncing the afrinic RPKI repo, then try to decode a cert file such as `repository/04E8B0D80F4D11E0B657D8931367AE7D/arin-to-afrinic.cer`. It claims the certificate is malformed but this used to work before this PR was merged.

**Comment by timbru** [comment]
This happens because some certificates use a UTF8 String rather than the mandated "PrintableString" for the issuer and/or subject names.

So, technically they are incorrect. However, we feel that this is probably a minor issue because names are not relevant really in the RPKI. Therefore we plan to do a follow-up release soon where we will accept these certificates, unless the 'strict' flag is used.

In addition we want to have a discussion in the IETF about this: should the standards be loosened in this regard, or.. should implementations be updated?

**Comment by partim** [comment]
This is being ‘fixed’ by #8.

**Comment by partim** [comment]
Thanks for reporting!

I think we only lost ARIN due to the Utf8String issue. Loosing APNIC with the first iteration of the fix was my fault.

That said, the --strict flag in the routinator now checks for DER encoding of signed objects and the correct formatting of issuer and subject. Just now, enabling it results in a drop from 58251 route prefixes to 13738.

**Pull request merged**
